#!/bin/bash

# 🗺️ Install ParishMap Component via Big Book Auto-Install
# ========================================================
# This script helps install ParishMap.tsx using the Big Book Auto-Install TSX Component system

echo "🗺️ Installing ParishMap Component via Big Book Auto-Install"
echo "=========================================================="
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting ParishMap component installation..."

# Check if ParishMap.tsx exists
if [ ! -f "ParishMap.tsx" ]; then
    echo "❌ ERROR: ParishMap.tsx not found in current directory"
    echo "💡 Please run this script from the directory containing ParishMap.tsx"
    echo "   Expected location: /a%3A/prod/"
    exit 1
fi

echo "✅ Found ParishMap.tsx in current directory"
echo ""

# Display component information
echo "📋 Component Information:"
echo "------------------------"
echo "• File: ParishMap.tsx"
echo "• Size: $(wc -c < ParishMap.tsx) bytes"
echo "• Lines: $(wc -l < ParishMap.tsx) lines"
echo "• Type: React TypeScript Component"
echo ""

echo "🎯 Big Book Auto-Install Features:"
echo "• Automatic installation to /src/components/bigbook/custom/"
echo "• Kebab-case route generation: /bigbook/parish-map"
echo "• Automatic menu integration in Big Book sidebar"
echo "• Component registry management"
echo "• Security validation and parsing"
echo ""

echo "📋 Installation Instructions:"
echo "=============================="
echo ""
echo "To install ParishMap.tsx using Big Book Auto-Install:"
echo ""
echo "1. 🌐 Open your browser and navigate to the Big Book interface"
echo "   URL: https://orthodoxmetrics.com/admin (or your admin interface)"
echo ""
echo "2. 🔓 Ensure you're logged in as super_admin or editor"
echo ""
echo "3. 📁 Navigate to the 'Big Book' section in the admin panel"
echo ""
echo "4. 🧩 Go to the 'Custom Components' tab"
echo ""
echo "5. 📤 Use one of these methods to upload ParishMap.tsx:"
echo ""
echo "   METHOD A - Drag & Drop:"
echo "   • Drag the ParishMap.tsx file from your file manager"
echo "   • Drop it onto the Big Book upload area"
echo "   • The TSX Component Installation Wizard will open automatically"
echo ""
echo "   METHOD B - File Upload:"
echo "   • Click the upload area in Big Book"
echo "   • Select ParishMap.tsx from the file picker"
echo "   • The TSX Component Installation Wizard will open automatically"
echo ""
echo "6. 🚀 In the TSX Component Installation Wizard:"
echo "   • Enable 'Big Book Auto-Install Mode' toggle"
echo "   • This will automatically:"
echo "     - Set target directory to: src/components/bigbook/custom"
echo "     - Enable registry integration"
echo "     - Generate route: /bigbook/parish-map"
echo "     - Add menu item to Big Book sidebar"
echo ""
echo "7. ✅ Click 'Install Component' to complete the installation"
echo ""
echo "8. 🔄 The system will:"
echo "   • Validate the component syntax and structure"
echo "   • Install it to the correct directory"
echo "   • Update the component registry"
echo "   • Add a menu item to the Big Book sidebar"
echo "   • Generate the route for accessing the component"
echo ""
echo "9. 🎉 Once installed, you can:"
echo "   • View the component at: /bigbook/parish-map"
echo "   • Access it from the Big Book sidebar menu"
echo "   • Manage it from the 'Custom Components' tab"
echo ""

echo "🔧 Expected Results After Installation:"
echo "======================================="
echo ""
echo "✅ Component will be installed at:"
echo "   front-end/src/components/bigbook/custom/ParishMap.tsx"
echo ""
echo "✅ Route will be available at:"
echo "   https://orthodoxmetrics.com/bigbook/parish-map"
echo ""
echo "✅ Menu item will appear in Big Book sidebar:"
echo "   📄 Parish Map"
echo ""
echo "✅ Component registry entry will be created in:"
echo "   front-end/src/config/bigbook-custom-components.json"
echo ""

echo "🚨 Prerequisites:"
echo "=================="
echo "• Server must be running on port 3001"
echo "• Backend Big Book Auto-Install API endpoints must be loaded"
echo "• User must have super_admin or editor permissions"
echo "• Frontend must be built with the latest changes"
echo ""

echo "💡 Troubleshooting:"
echo "==================="
echo ""
echo "If 'Install Component' button is greyed out:"
echo "• Check browser console for errors"
echo "• Ensure you're logged in with proper permissions"
echo "• Verify server is running and accessible"
echo ""
echo "If installation fails:"
echo "• Check the Big Book console output for error details"
echo "• Verify the component has valid React TypeScript syntax"
echo "• Ensure all dependencies are available"
echo ""
echo "For component viewing issues:"
echo "• The component viewer is currently temporarily disabled for debugging"
echo "• Components can still be installed and accessed via direct routes"
echo "• Use the route: /bigbook/parish-map to access after installation"
echo ""

echo "📝 Component Dependencies:"
echo "=========================="
echo "The ParishMap component requires these dependencies:"
echo "• react-leaflet (for map functionality)"
echo "• leaflet (base mapping library)"
echo "• react-leaflet-markercluster (for marker clustering)"
echo "• @headlessui/react (for UI components)"
echo "• @heroicons/react (for icons)"
echo ""
echo "⚠️  Note: The auto-install system will attempt to install missing dependencies"
echo "   automatically. If installation fails due to missing deps, you may need"
echo "   to install them manually in the frontend."
echo ""

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Script completed"
echo ""
echo "🎯 Next Step: Open your browser and follow the installation instructions above!" 