#!/bin/bash

# 🗺️ Browser-Guided ParishMap Installation
# ========================================
# Since you're already logged in as superadmin, this guides you through browser installation

echo "🗺️ ParishMap Component - Browser Installation Guide"
echo "=================================================="
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Browser-guided installation..."

# Check if ParishMap.tsx exists
if [ ! -f "ParishMap.tsx" ]; then
    echo "❌ ERROR: ParishMap.tsx not found in current directory"
    echo "💡 Current directory: $(pwd)"
    exit 1
fi

echo "✅ Found ParishMap.tsx ($(wc -c < ParishMap.tsx) bytes)"
echo ""

echo "🎯 Since you're already logged in as superadmin, let's use the browser method:"
echo ""
echo "📋 STEP-BY-STEP BROWSER INSTALLATION:"
echo "====================================="
echo ""
echo "1. 🌐 You're already in the admin interface - perfect!"
echo "   Current page: Admin Settings"
echo ""
echo "2. 📁 Navigate to Big Book:"
echo "   • Look for 'OM Big Book' or 'Big Book' in the left sidebar"
echo "   • Click on it to open the Big Book interface"
echo ""
echo "3. 🧩 Go to Custom Components tab:"
echo "   • Once in Big Book, look for tabs at the top"
echo "   • Click on the 'Custom Components' tab"
echo ""
echo "4. 📤 Upload ParishMap.tsx:"
echo "   • You'll see an upload area with drag & drop functionality"
echo "   • Either:"
echo "     - Drag ParishMap.tsx from your file manager to the upload area"
echo "     - OR click the upload area and select ParishMap.tsx"
echo ""
echo "5. 🚀 Use Big Book Auto-Install Mode:"
echo "   • The TSX Component Installation Wizard will open automatically"
echo "   • IMPORTANT: Toggle ON the 'Big Book Auto-Install Mode' switch"
echo "   • This will:"
echo "     ✅ Set target directory to: src/components/bigbook/custom"
echo "     ✅ Enable registry integration"
echo "     ✅ Generate route: /bigbook/parish-map"
echo "     ✅ Add menu item to Big Book sidebar"
echo ""
echo "6. ✅ Install:"
echo "   • Click 'Install Component' button"
echo "   • Wait for the installation to complete"
echo "   • You should see success messages in the console"
echo ""
echo "7. 🎉 Verify Installation:"
echo "   • Look for 'Parish Map' in the Big Book sidebar menu"
echo "   • You can access it at: /bigbook/parish-map"
echo ""

echo "💡 QUICK NAVIGATION HELP:"
echo "========================"
echo ""
echo "If you can't find 'Big Book' in the sidebar:"
echo "• Look for 'OM Big Book', 'Big Book', or a book icon 📚"
echo "• It might be under 'System Administration' or 'Settings'"
echo "• Try searching for 'big book' in the page"
echo ""
echo "If the upload area doesn't appear:"
echo "• Make sure you're on the first tab 'Imports & Scripts'"
echo "• Look for a drag-and-drop area with cloud upload icon"
echo "• The area should say 'Drop files here or click to upload'"
echo ""

echo "🔧 EXPECTED RESULTS AFTER INSTALLATION:"
echo "======================================="
echo ""
echo "✅ Component installed at: src/components/bigbook/custom/ParishMap.tsx"
echo "✅ Route created: https://orthodoxmetrics.com/bigbook/parish-map"
echo "✅ Menu item: 'Parish Map' in Big Book sidebar"
echo "✅ Registry updated: bigbook-custom-components.json"
echo ""

echo "📋 COMPONENT FEATURES YOU'LL GET:"
echo "================================="
echo ""
echo "🗺️ Interactive Orthodox Parish Map with:"
echo "• Leaflet-based mapping with marker clustering"
echo "• Parish filtering by jurisdiction, state, diocese, city"
echo "• Mock parish data for demonstration"
echo "• Responsive design for mobile and desktop"
echo "• Popup details for each parish"
echo "• Custom Orthodox church icons"
echo ""

echo "🚨 TROUBLESHOOTING:"
echo "==================="
echo ""
echo "If 'Install Component' button is greyed out:"
echo "• Check browser console (F12) for any errors"
echo "• Make sure the file uploaded correctly"
echo "• Try refreshing the page and uploading again"
echo ""
echo "If installation fails:"
echo "• Check the Big Book console output for error messages"
echo "• Make sure you toggled ON 'Big Book Auto-Install Mode'"
echo "• Verify you're on the 'Custom Components' tab"
echo ""
echo "If component doesn't appear in sidebar:"
echo "• Refresh the page after installation"
echo "• Check the 'Custom Components' tab to see if it's listed"
echo "• Try accessing directly: /bigbook/parish-map"
echo ""

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Guide complete!"
echo ""
echo "🎯 Ready to install! Follow the steps above in your browser."
echo ""
echo "💬 The browser method works best since you're already authenticated!"
echo "   Command line installation requires session cookies that aren't available from shell." 