#!/bin/bash

# 🗺️ Test ParishMap Route After Routing Fix
# ==========================================
# This script rebuilds the frontend and tests ParishMap access

echo "🗺️ ParishMap Route Testing"
echo "=========================="
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Testing ParishMap after routing fix..."
echo ""

echo "📋 Current Status:"
echo "✅ ParishMap.tsx installed at: front-end/src/components/bigbook/custom/ParishMap.tsx" 
echo "✅ Registry configured: front-end/src/config/bigbook-custom-components.json"
echo "✅ BigBookDynamicRoute component created"
echo "✅ Router.tsx updated with /bigbook/:componentId routes"
echo ""

echo "🔄 Step 1: Frontend Rebuild Required"
echo "===================================="
echo ""
echo "The routing changes require a frontend rebuild to take effect."
echo ""
echo "💡 Please run these commands:"
echo ""
echo "cd front-end"
echo "NODE_OPTIONS=\"--max-old-space-size=4096\" npm run build --legacy-peer-deps"
echo ""
echo "⏳ This may take several minutes..."
echo ""

echo "🌐 Step 2: Test ParishMap Access" 
echo "==============================="
echo ""
echo "After the frontend rebuild completes, test these URLs:"
echo ""
echo "1. **Direct ParishMap URL**:"
echo "   https://orthodoxmetrics.com/bigbook/parish-map"
echo ""
echo "2. **Expected Behavior**:"
echo "   - Page should load with 'Loading Big Book Component...' message"
echo "   - Should fetch registry from /api/bigbook/custom-components-registry"
echo "   - Should dynamically import and render ParishMap component"
echo "   - Should show interactive Orthodox parish map with filters"
echo ""

echo "🔍 Step 3: Debugging Information"
echo "==============================="
echo ""
echo "If the route still shows 404:"
echo ""
echo "1. **Check Browser Console** for errors:"
echo "   - Open Developer Tools (F12)"
echo "   - Look for import errors or component loading issues"
echo ""
echo "2. **Verify Registry API**:"
echo "   - Test: https://orthodoxmetrics.com/api/bigbook/custom-components-registry"
echo "   - Should return JSON with parish-map component"
echo ""
echo "3. **Check Network Tab**:"
echo "   - Verify ParishMap component import attempts"
echo "   - Look for any 404s or failed imports"
echo ""

echo "📊 Expected Registry Content:"
echo "============================"
echo ""
echo "The API should return:"
echo "{"
echo "  \"components\": {"
echo "    \"parish-map\": {"
echo "      \"id\": \"parish-map\","
echo "      \"name\": \"ParishMap\","
echo "      \"path\": \"src/components/bigbook/custom/ParishMap.tsx\","
echo "      \"route\": \"/bigbook/parish-map\","
echo "      \"displayName\": \"Parish Map\""
echo "    }"
echo "  }"
echo "}"
echo ""

echo "🎯 Success Indicators:"
echo "======================"
echo ""
echo "✅ **Route Found**: No more 404 error at /bigbook/parish-map"
echo "✅ **Component Loading**: Shows 'Loading Big Book Component...' spinner"
echo "✅ **Registry Fetch**: Successfully loads component metadata"
echo "✅ **Component Import**: Dynamically imports ParishMap.tsx"
echo "✅ **Map Rendering**: Shows interactive Leaflet map with parish markers"
echo "✅ **Filters Working**: Can filter parishes by jurisdiction, state, etc."
echo ""

echo "⚠️ Possible Issues:"
echo "=================="
echo ""
echo "1. **Import Path Issues**: BigBookDynamicRoute may need path adjustments"
echo "2. **Dependencies Missing**: react-leaflet libraries may need installation"
echo "3. **Build Cache**: May need to clear browser cache after rebuild"
echo ""

echo "🔧 Troubleshooting Commands:"
echo "============================"
echo ""
echo "If still having issues, try:"
echo ""
echo "# Clear frontend cache and rebuild"
echo "cd front-end"
echo "rm -rf dist/"
echo "rm -rf node_modules/.vite/"
echo "NODE_OPTIONS=\"--max-old-space-size=4096\" npm run build --legacy-peer-deps"
echo ""
echo "# Test registry API directly"
echo "curl -s https://orthodoxmetrics.com/api/bigbook/custom-components-registry | head -20"
echo ""
echo "# Check if dependencies are installed"
echo "cd front-end"
echo "npm list react-leaflet leaflet react-leaflet-markercluster"
echo ""

echo "🚀 Next Steps After Success:"
echo "============================"
echo ""
echo "Once ParishMap loads successfully:"
echo ""
echo "1. **Test all map features**:"
echo "   - Zoom, pan, marker clustering"
echo "   - Filter by jurisdiction, state, diocese, city"
echo "   - Popup information display"
echo ""
echo "2. **Check Big Book integration**:"
echo "   - Verify if menu item appears in Big Book sidebar"
echo "   - Test navigation from Big Book UI"
echo ""
echo "3. **Dependencies verification**:"
echo "   - Ensure all mapping libraries work correctly"
echo "   - No console errors during map interaction"
echo ""

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Test guide complete!"
echo ""
echo "🎯 **Main Action Required**: Rebuild frontend with the commands above!"
echo "   This should fix the 404 error and make ParishMap accessible." 