#!/bin/bash

echo "🔐 Frontend Authentication Checker"
echo "=================================="
echo "This script helps check if you're properly logged in to the frontend."
echo ""

# Function to log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "Checking frontend authentication status..."

echo ""
log "=== AUTHENTICATION VERIFICATION ==="
echo ""
echo "To verify you're logged in with proper permissions:"
echo ""
echo "1. 🌐 OPEN YOUR FRONTEND:"
echo "   • http://localhost:3000 (development)"
echo "   • https://orthodoxmetrics.com (production)"
echo ""
echo "2. 🔍 CHECK YOUR LOGIN STATUS:"
echo "   • Look for your username in the top-right corner"
echo "   • Make sure you're logged in (not seeing a login form)"
echo ""
echo "3. 👤 VERIFY YOUR USER ROLE:"
echo "   • Go to Admin Settings (or Admin Dashboard)"
echo "   • If you can see admin options, you have the right permissions"
echo "   • Required roles: super_admin OR editor"
echo ""
echo "4. 🧪 TEST WITH BIG BOOK:"
echo "   • Go to Admin Settings → OM Big Book"
echo "   • Try uploading any .tsx file"
echo "   • Check the console messages in the wizard"
echo ""

echo ""
log "=== CONSOLE MESSAGE DIAGNOSTICS ==="
echo ""
echo "When you upload a TSX file, look for these messages:"
echo ""
echo "✅ GOOD MESSAGES (means you're authenticated):"
echo "   '🔍 Parsing .tsx file: [filename]'"
echo "   '✅ Component parsed successfully: [ComponentName]'"
echo ""
echo "❌ BAD MESSAGES (means authentication issues):"
echo "   '🔐 Authentication required: Please log in as super_admin or editor'"
echo "   '❌ Server error: HTTP 401 - Unauthorized'"
echo "   '❌ Server error: HTTP 403 - Forbidden'"
echo ""

echo ""
log "=== TROUBLESHOOTING STEPS ==="
echo ""
echo "If you're getting authentication errors:"
echo ""
echo "1. 🔄 REFRESH THE PAGE:"
echo "   • Sometimes sessions expire"
echo "   • Hard refresh: Ctrl+F5 or Cmd+Shift+R"
echo ""
echo "2. 🔑 RE-LOGIN:"
echo "   • Log out completely"
echo "   • Log back in with a super_admin or editor account"
echo ""
echo "3. 🍪 CHECK COOKIES/SESSION:"
echo "   • Open browser dev tools (F12)"
echo "   • Check Application/Storage → Cookies"
echo "   • Look for session cookies for your domain"
echo ""
echo "4. 🧪 TEST BASIC API ACCESS:"
echo "   • While logged in, open browser console (F12)"
echo "   • Run: fetch('/api/status', {credentials: 'include'}).then(r => r.json()).then(console.log)"
echo "   • Should return server status, not authentication error"
echo ""

echo ""
log "=== FRONTEND BUILD CHECK ==="
echo ""
echo "If you made changes and they're not working:"
echo ""
echo "1. 🏗️ REBUILD THE FRONTEND:"
echo "   • cd front-end"
echo "   • npm run build (with --legacy-peer-deps if needed)"
echo "   • Wait for build to complete"
echo ""
echo "2. 🔄 REFRESH BROWSER:"
echo "   • Hard refresh the page"
echo "   • Clear browser cache if needed"
echo ""

echo ""
log "=== NEXT STEPS ==="
echo ""
echo "After verifying authentication:"
echo "1. ✅ You should be logged in as super_admin/editor"
echo "2. ✅ Try uploading a TSX file in Big Book"
echo "3. ✅ Look for the improved error messages"
echo "4. ✅ Install button should enable after successful parsing"

echo ""
log "=== CHECK COMPLETE ==="
echo ""
echo "If you're still having issues after following these steps,"
echo "please share the console messages from the TSX upload wizard." 