name: TypeScript Type Check

on:
  push:
    branches: [ main, develop, refactor/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dir: [front-end, server]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        
    - name: Install dependencies
      run: npm install
      working-directory: ./prod/${{ matrix.dir }}
      
    - name: Run TypeScript type check
      run: npx tsc --noEmit
      working-directory: ./prod/${{ matrix.dir }}
